### ISSUE TITLE
approval members manual / confirm email

### ISSUE THREAD

**Issue by codeplay-code** [madromas/esoTalk-v3#9]
Something Went Wrong
The Forum has encountered a fatal error.

$config["plugin.SMTP.server"] = 'smtp.gmail.com';
$config["plugin.SMTP.username"] = 'mygmail';
$config["plugin.SMTP.password"] = 'mypass';
$config["plugin.SMTP.port"] = '587';
$config["plugin.SMTP.auth"] = 'ssl';

**Comment by codeplay-code** [comment]
mail_test.php

if(sendEmail(
    '**internmail@gmail.com**', 
    sprintf( T("email.".$type.".subject"), 'Max Mustermann' ),
    sprintf( T("email.".$type.".body"), C("esoTalk.forumTitle"), C("esoTalk.baseURL").'user/login' ), 
    C("esoTalk.baseURL").'user/login',
    TRUE)
)echo '<h1><tt>OK '.time();else echo '<h1><tt>ERROR';
#*/
im change my mail ?

**Comment by madromas** [comment]
I don't think SMTP works with gmail. I'm not positive.

Have you used gmail on any other SMTP platforms?

**Comment by codeplay-code** [comment]
I tried gmail and my host's email (hostinger) doesn't work either

**Comment by madromas** [comment]
How are you testing it, mail_test.php or in actual script itself?
